# Generated by Django 6.0.8 on 2026-08-24 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('api', 'API'), ('ats', 'ATS'), ('scraper', 'Scraper'), ('manual', 'Manual')], max_length=20)),
                ('base_url', models.URLField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SkillKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=120, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('remote_type', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('min_years_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('max_years_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('extracted_requirements', models.JSONField(blank=True, default=list)),
                ('extraction_version', models.CharField(blank=True, max_length=20)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('employment_type', models.CharField(blank=True, max_length=120)),
                ('team', models.CharField(blank=True, max_length=160)),
                ('department', models.CharField(blank=True, max_length=160)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='jobs_job_title_0e1e41_idx'), models.Index(fields=['company'], name='jobs_job_company_73ae7f_idx'), models.Index(fields=['active'], name='jobs_job_active_b1dcb2_idx'), models.Index(fields=['posted_at'], name='jobs_job_posted__7edcdf_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('apply_url', models.URLField(blank=True, max_length=1000)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='jobs.job')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='jobs.jobsource')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'active'], name='jobs_joblis_source__3540c0_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_listing_per_source')],
            },
        ),
    ]
