# Generated by Django 6.0.8 on 2026-08-24 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('apply_url', models.URLField(blank=True, max_length=1000)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='jobs.job')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_occurrences', to='jobs.jobsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_occurrence_per_source')],
            },
        ),
    ]
