# Generated by Django 6.0.8 on 2026-08-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_joboccurrence'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='joboccurrence',
            name='unique_occurrence_per_source',
        ),
        migrations.DeleteModel(
            name='JobOccurrence',
        ),
    ]
