# Generated by Django 6.0.8 on 2026-08-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_joboccurrence_unique_occurrence_per_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsource',
            name='last_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobsource',
            name='validation_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobsource',
            name='validation_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='unknown', max_length=20),
        ),
    ]
