# Generated by Django 6.0.8 on 2026-08-24 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('minimum_score', models.PositiveSmallIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('rule_type', models.CharField(choices=[('filter', 'Filter'), ('score', 'Score')], max_length=10)),
                ('field', models.CharField(choices=[('title', 'Title'), ('description', 'Description'), ('location_text', 'Location'), ('remote_type', 'Remote type'), ('min_years_experience', 'Minimum required experience'), ('skills', 'Skills'), ('company', 'Company')], max_length=40)),
                ('operator', models.CharField(choices=[('contains', 'Contains'), ('not_contains', 'Does not contain'), ('in', 'In'), ('lte', 'Less than or equal'), ('gte', 'Greater than or equal'), ('eq', 'Equals')], max_length=20)),
                ('value', models.JSONField()),
                ('required', models.BooleanField(default=False)),
                ('weight', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='searches.searchprofile')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible', models.BooleanField(default=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('matched_weight', models.IntegerField(default=0)),
                ('possible_weight', models.IntegerField(default=0)),
                ('reasons', models.JSONField(default=list)),
                ('rejection_reasons', models.JSONField(default=list)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='searches.searchprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'eligible', 'score'], name='searches_jo_profile_85689d_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'job'), name='unique_job_match_per_profile')],
            },
        ),
    ]
