# Generated by Django 6.0.8 on 2026-08-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrule',
            name='missing_behavior',
            field=models.CharField(choices=[('ignore', 'Ignore'), ('fail', 'Fail')], default='ignore', max_length=10),
        ),
    ]
