# Generated by Django 6.0.8 on 2026-08-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0002_searchrule_missing_behavior'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprofile',
            name='discovery_locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='discovery_titles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
