# Generated by Django 6.0.8 on 2026-08-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0003_searchprofile_discovery_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprofile',
            name='discovery_primary_titles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
