# Generated by Django 6.0.8 on 2026-08-25 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('searches', '0003_searchprofile_discovery_locations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('queries', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_runs', to='searches.searchprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveredSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('provider', models.CharField(choices=[('lever', 'Lever'), ('greenhouse', 'Greenhouse'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('provider_identifier', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('registered', 'Registered'), ('ignored', 'Ignored'), ('invalid', 'Invalid')], default='discovered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='discovery.discoveryrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'url'), name='unique_discovered_url_per_run')],
            },
        ),
    ]
