# Generated by Django 6.0.8 on 2026-08-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveredsource',
            name='provider_region',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
